apiVersion: skaffold/v4beta6
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: eco-plating-387811
  artifacts:
    - image: us.gcr.io/eco-plating-387811/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/eco-plating-387811/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'app/**/*.{js,ts,jsx,tsx,mdx}'
            dest: .
          - src: 'components/**/*.{js,ts,jsx,tsx,mdx}'
            dest: .