name: auth-tests

on: 
  pull_request:
    branches:
      - 'main'
    paths:
      - 'ticketing/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd ticketing/auth
          npm install
          npm run test:ci