name: expiration-tests

on: 
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - runs: cd ticketing/expiration && npm install && npm run test:ci
