name: expiration-tests

on:
  push:
    branches:
      - 'main'
    paths:
      - 'ticketing/expiration/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd ticketing/expiration
          npm install
          npm run test:ci